name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install pandoc

      - name: Generate PDF
        run: |
          pandoc demo.md -o demo.pdf
